name: Nightly Build

env:
  FILE_NAME: ""

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

permissions:
  actions: write
  contents: write
  packages: read

jobs:
  nightly-build:
    runs-on: ubuntu-latest
    container: 
      image: xeno178531/godot-ci:latest
    steps: 
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Project version update  
        run:  python3 .github/scripts/main.py
        
      - name: Install dependencies for Linux export
        run: |
          apt-get update
          apt-get install -y libfontconfig1 libxcursor1 libxinerama1 libxi6
      - name: Import Project Assets
        run: |
          godot --headless --editor --quit
      - name: Download Godot Export Templates
        run: |
          mkdir -p /github/home/.local/share/godot/export_templates/4.7.rc2/
          curl -L -o templates.tpz https://github.com/godotengine/godot-builds/releases/download/4.7-rc2/Godot_v4.7-rc2_export_templates.tpz
          unzip templates.tpz
          mv templates/* /github/home/.local/share/godot/export_templates/4.7.rc2/
          rm -rf templates templates.tpz
      
      - name: Build project for windows
        run: |
          mkdir -p build/windows
          godot --export-release "Windows Desktop" build/windows/${{ env.FILE_NAME }}.exe --path . --headless
      - name: Build project for linux
        run: |
          mkdir -p build/linux
          godot --export-release "Linux" build/linux/${{env.FILE_NAME}}.x86_64 --path . --headless
      
      - name: Release build
        uses: softprops/action-gh-release@v1
        with:
          tag_name: nightly
          name: "Nightly Build"
          body: "This is a nightly build of the game from: ${{ github.event.repository.updated_at }}."
          prerelease: true
          files: |
            build/windows/${{env.FILE_NAME}}.exe
            build/linux/${{env.FILE_NAME}}.x86_64
